server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/selmag_catalogue_db
    username: catalogue_user
    password: password
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag