spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/selmag_pg
    username: user
    password: password
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    sql: info
server:
  port: 8081
