server:
  port: 8083

selmag:
  service:
    catalogue:
      url: http://localhost:8081/catalogue-api/products
    feedback:
      product-reviews:
        url: http://localhost:8084/feedback-api/product-reviews
      favourite-products:
        url: http://localhost:8084/feedback-api/favourite-products
